apiVersion: v1
kind: ServiceAccount
metadata:
  name: pekko-cluster-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pekko-cluster-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pekko-cluster-pod-reader-binding
subjects:
  - kind: ServiceAccount
    name: pekko-cluster-sa
roleRef:
  kind: Role
  name: pekko-cluster-pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: pekko-cluster
  labels:
    app: pekko-cluster
spec:
  clusterIP: None
  selector:
    app: pekko-cluster
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: remoting
      port: 25520
      targetPort: 25520
    - name: management
      port: 8558
      targetPort: 8558
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pekko-cluster
spec:
  serviceName: pekko-cluster
  replicas: 2
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: pekko-cluster
  template:
    metadata:
      labels:
        app: pekko-cluster
    spec:
      serviceAccountName: pekko-cluster-sa
      containers:
        - name: pekko-node
          image: sample-cluster-kotlin:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 25520
              name: remoting
            - containerPort: 8558
              name: management
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER_PORT
              value: "8080"
            - name: CLUSTER_HOSTNAME
              value: "$(POD_NAME).pekko-cluster.default.svc.cluster.local"
            - name: CLUSTER_PORT
              value: "25520"
            - name: MANAGEMENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MANAGEMENT_PORT
              value: "8558"
            - name: CLUSTER_MIN_NR
              value: "2"
            - name: CLUSTER_BOOTSTRAP_SERVICE_NAME
              value: "pekko-cluster"
            - name: CLUSTER_BOOTSTRAP_REQUIRED_CONTACT_POINTS
              value: "2"
            - name: CLUSTER_BOOTSTRAP_PORT_NAME
              value: "management"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.default.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "cluster-kotlin-events"
            - name: KAFKA_GROUP_ID_PREFIX
              value: "cluster-kotlin-group"
            - name: CAFE24_BUCKET_CAPACITY
              value: "10"
            - name: CAFE24_LEAK_RATE_PER_SECOND
              value: "2"
            - name: CAFE24_PER_MALL_MAX_RPS
              value: "2"
          readinessProbe:
            httpGet:
              path: /api/heath
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
